const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,text)=>{try{if(!['http:','https:'].includes(new URL(url).protocol))return escape(text);}catch{return escape(text);}return `<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(text)} <span aria-hidden="true">↗</span></a>`;};
let baseDb,db,c,tab='history',selected=2,edgeSelected=null,identity='all',filter='all',busy=false,error='',query='',creation=null,zoom=1,showFailures=false;
const tabs=[['history','历史演化','01'],['solutions','成熟方案','02'],['sources','首发源地图','03'],['access','我能获得','04'],['frontier','创新边界','05']];
const icon=['◈','⌘','▱','⤴','◉','▤','◇'];
const pricing={open:'开源 · 可自建',free:'有免费使用路径',freemium:'免费 / 附加付费',paid:'付费',student:'学生资格'};
function sourceRefs(ids){return `<div class="refs">${ids.map(id=>{const s=db.sources.find(s=>s.id===id);return s?link(s.url,s.name):'';}).join('')}</div>`;}
function navigate(id){const next=db.cases.find(x=>x.id===id);if(!next)return;for(const key of ['resources','sources','access'])db[key]=structuredClone(baseDb[key]);c=next;query=c.want;selected=2;edgeSelected=null;creation=null;error='';zoom=1;showFailures=false;tab='history';history.replaceState(null,'',`#${c.id}`);render();}
function shell(){return `<aside class="sidebar"><a href="#" class="brand" id="home"><span class="brand-symbol">⌁</span><span>Sourcever<small>人类能力图谱</small></span></a><div class="workspace-label">探索工作台 <span>V 0.1</span></div><button class="new-query" id="new-query">＋ <span>探索一个新想法</span><kbd> / </kbd></button><div class="rail-title">公开探索案例 <span>${db.cases.length.toString().padStart(2,'0')}</span></div><nav class="topics" aria-label="探索案例">${db.cases.map((x,i)=>`<button class="topic ${x.id===c.id?'active':''}" data-topic="${x.id}"><span>${icon[i%icon.length]}</span>${escape(x.title)}${x.id===c.id?'<b>↗</b>':''}</button>`).join('')}</nav><div class="rail-note"><span class="orbit">◎</span><p>别从零开始。<br>从人类已经走到的地方继续。</p></div><div class="sidebar-bottom"><button id="bill">↗ &nbsp;互联网权利法案</button><span>OPEN KNOWLEDGE, OPEN POSSIBILITY.</span></div></aside><div class="workspace"><header class="topbar"><span><span class="muted">工作台</span><i>/</i>${escape(c.title)}</span><div><span class="status-dot"></span>${db.aiEnabled?'AI 分析已连接':'精选案例模式'}<button id="about" class="text-button">关于图谱 ↗</button></div></header><main id="main"><section class="query-area"><div class="eyebrow">BEFORE THE FIRST LINE OF CODE</div><div class="heading-row"><h1>你想做到什么？</h1><span>先理解世界，再开始创造。</span></div><form id="query-form"><label class="sr-only" for="query">描述你的需求</label><span class="query-symbol">⌕</span><input id="query" name="query" maxlength="600" minlength="2" required value="${escape(query)}" placeholder="例如：我想做一个团队在线文档工具" autocomplete="off"><button type="submit" ${busy?'disabled':''}>${busy?'正在分析…':'看看人类已经做到哪里'} <span>↗</span></button></form><div class="query-meta"><span>${c.mode==='ai'?'AI 研究草稿 · 尚未核验来源':'精选公开案例 · 输入相近需求将匹配相关案例'}</span><button id="custom-ai" class="text-button" ${!db.aiEnabled||busy?'disabled':''}>${db.aiEnabled?'针对输入进行 AI 分析 ↗':'配置 AI 后可探索任意需求'}</button></div>${error?`<div class="error" role="alert">${escape(error)}</div>`:''}</section><section class="need-card"><span class="need-icon">◎</span><div><div class="eyebrow">真正想解决的问题 <span>UNDERLYING NEED</span></div><h2>${escape(c.need)}</h2></div><span class="badge">${c.mode==='ai'?'待核验草稿':'需求抽象'}</span></section><nav class="tabs" aria-label="探索阶段">${tabs.map(([id,name,no])=>`<button data-tab="${id}" aria-current="${id===tab?'page':'false'}" class="${id===tab?'active':''}"><span>${no}</span>${name}</button>`).join('')}</nav><div id="view">${view()}</div><footer><span>HUMAN CAPABILITY GRAPH <i>·</i> 先继承，再创造。</span><span>${c.mode==='ai'?'生成于':'编辑快照'} ${escape(c.updatedAt)} <button id="export" class="text-button">导出探索笔记 ↓</button></span></footer></main></div><dialog id="dialog"><button class="dialog-close" aria-label="关闭对话框">×</button><div id="dialog-content"></div></dialog>`;}
function view(){if(tab==='history')return historyView();if(tab==='solutions')return solutionsView();if(tab==='sources')return sourcesView();if(tab==='access')return accessView();return frontierView();}
function historyView(){const n=c.nodes[selected]||c.nodes[0];const e=edgeSelected!==null?c.edges[edgeSelected]:null;return `<div class="section-head"><div><h2>人类是怎样走到这里的<span class="small-label">EVOLUTION MAP</span></h2><p>沿着每一次跃迁，理解新能力为什么出现。</p></div><button class="outline ${showFailures?'selected':''}" id="failures">${showFailures?'返回演化地图':'查看失败路线'} <span>${c.failures.length.toString().padStart(2,'0')}</span></button></div>${showFailures?failuresView():`<div class="map-layout"><section class="map-panel" aria-label="解决方案进化图"><div class="map-top"><span><b class="legend-dot"></b> 主演化路径</span><span><b class="legend-dot branch"></b> 并行探索 / 汇合</span><small>点击节点或连线标签</small></div><div class="map-scroll"><svg viewBox="0 0 710 ${c.nodes.length===6?470:Math.ceil(c.nodes.length/3)*140+45}" class="graph zoom-${zoom}" role="group" aria-label="${escape(c.title)}演化关系图">${graph()}</svg></div><div class="map-bottom"><span>◌ &nbsp;${c.nodes.length} 个历史节点 · ${c.edges.length} 次能力跃迁</span><div class="zoom-controls"><button id="zoom-out" aria-label="缩小地图">−</button><span>${zoom===1?'100%':'125%'}</span><button id="zoom-in" aria-label="放大地图">＋</button></div></div></section><aside class="detail-panel" aria-label="选中节点详情"><div class="detail-kicker">${e?'关键跃迁 / WHY THE ARROW':'历史节点 / '+String(selected+1).padStart(2,'0')}<span>↗</span></div><h3>${escape(e?c.nodes.find(n=>n.id===e.toId)?.name:n.name)}</h3><div class="detail-era">${escape(e?'演化原因 · 编辑综合解释':n.era)}</div>${e?`<dl><dt>旧方案解决了什么</dt><dd>${escape(e.oldCapability)}</dd><dt>还有什么没解决</dt><dd>${escape(e.oldLimit)}</dd><dt class="green">促成变化的条件</dt><dd>${escape(e.why)}</dd><dt>新增能力</dt><dd>${escape(e.newCapability)}</dd><dt>新的问题</dt><dd>${escape(e.newProblem)}</dd></dl>`:`<dl><dt>解决了什么</dt><dd>${escape(n.solves)}</dd><dt>为什么出现</dt><dd>${escape(n.reason)}</dd><dt>仍然存在的限制</dt><dd>${escape(n.limitation)}</dd><dt>代表产品 / 技术</dt><dd>${escape(n.representative)}</dd></dl>`}<p class="evidence-note">${escape(e?.evidence||n.evidence)}</p>${sourceRefs(e?.sourceIds||n.sourceIds)}<button class="detail-action" id="node-resources">查看今天可复用的能力 <span>→</span></button></aside></div>`}<div class="insight-strip"><span>✦</span><p><strong>历史不是一条直线。</strong>不同路线会并行、分叉，也会重新汇合。图中连线表示能力演化的解释，不代表已证实的直接继承。</p><button data-tab="solutions">今天能用什么 →</button></div>`;}
function positions(){const count=c.nodes.length;return c.nodes.map((n,i)=>{if(count===6)return [[36,35],[36,160],[285,95],[36,320],[285,285],[518,285]][i];return [35+(i%3)*230,35+Math.floor(i/3)*140];});}
function graph(){const p=positions();const width=168,height=78;return `<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#577181"/></marker></defs>${c.edges.map((e,i)=>{const ai=c.nodes.findIndex(n=>n.id===e.fromId),bi=c.nodes.findIndex(n=>n.id===e.toId);if(ai<0||bi<0)return '';const a=p[ai],b=p[bi];const vertical=a[0]===b[0];const x1=a[0]+(vertical?width/2:width),y1=a[1]+(vertical?height:height/2),x2=b[0]+(vertical?width/2:0),y2=b[1]+(vertical?0:height/2);const mx=(x1+x2)/2,my=(y1+y2)/2;const path=vertical?`M${x1} ${y1}L${x2} ${y2}`:`M${x1} ${y1} C${mx} ${y1},${mx} ${y2},${x2} ${y2}`;return `<g class="graph-edge ${edgeSelected===i?'chosen':''}" data-edge="${i}" role="button" tabindex="0" aria-label="解释 ${escape(c.nodes[ai].name)} 到 ${escape(c.nodes[bi].name)} 的跃迁"><path d="${path}" class="edge-hit"/><path d="${path}" class="edge-line ${e.type==='forked_into'?'dashed':''}" marker-end="url(#arrow)"/><rect x="${mx-23}" y="${my-10}" width="46" height="20" rx="6"/><text x="${mx}" y="${my+4}" text-anchor="middle">${e.type==='forked_into'?'分叉':'为什么'}</text></g>`;}).join('')}${c.nodes.map((n,i)=>`<g class="graph-node ${selected===i&&edgeSelected===null?'chosen':''} ${n.lane===1?'branch-node':''}" data-node="${i}" role="button" tabindex="0" aria-label="${escape(n.name)}：${escape(n.solves)}" transform="translate(${p[i][0]},${p[i][1]})"><rect width="${width}" height="${height}" rx="10"/><text class="node-era" x="15" y="24">${escape(n.era)}</text><text class="node-name" x="15" y="49">${escape(n.name.length>10?n.name.slice(0,10)+"…":n.name)}</text><circle cx="151" cy="19" r="3"/></g>`).join('')}<text class="map-annotation" x="36" y="445">FROM WHAT EXISTED → TO WHAT IS POSSIBLE</text>`;}
function failuresView(){return `<div class="failure-area">${c.failures.length?c.failures.map(f=>`<article class="failure-card"><span class="badge amber">${escape(f.when)} · 停止 / 被替代</span><h3>${escape(f.name)}</h3><dl>${[['当时为什么合理',f.promise],['创新在哪里',f.innovation],['结果与原因',f.outcome+' '+f.reason],['方向错了，还是时间太早？',f.lesson]].map(([a,b])=>`<dt>${a}</dt><dd>${escape(b)}</dd>`).join('')}</dl>${sourceRefs(f.sourceIds)}</article>`).join(''):`<div class="empty"><span>⌕</span><h3>这块历史，仍需要补全。</h3><p>${escape(c.failureNote)}</p><p>下一步：寻找关闭公告、创始人复盘与用户迁移记录。</p></div>`}</div>`;}
function selectedResources(){return db.resources.filter(r=>c.resourceIds.includes(r.id));}
function solutionsView(){const rs=selectedResources().filter(r=>filter==='all'||(filter==='open'?r.pricing==='open':['free','freemium'].includes(r.pricing)));return `<div class="section-head"><div><h2>今天能用什么<span class="small-label">READY TO REUSE</span></h2><p>把成熟的基础能力交给现成方案。</p></div><div class="filters" aria-label="价格筛选">${[['all','全部'],['open','开源'],['free','含免费路径']].map(([v,t])=>`<button class="${filter===v?'selected':''}" data-filter="${v}">${t}</button>`).join('')}</div></div><div class="cards">${rs.map(r=>`<article class="resource-card"><div class="resource-top"><span class="resource-mark">${escape(r.name[0])}</span><span class="badge">${escape(pricing[r.pricing]||r.pricing)}</span></div><h3>${escape(r.name)}</h3><p>${escape(r.description)}</p><div class="resource-metadata">${escape(r.status)} · ${escape(c.nodes.find(n=>n.id===r.solutionId)?.name)}</div><div class="card-actions">${link(r.url,'官方入口')}<button data-access="${escape(r.id)}">如何获得 →</button></div></article>`).join('')||'<div class="empty"><h3>暂无符合条件的方案</h3><p>切换筛选查看其他可复用能力。</p></div>'}</div><p class="footnote">价格与状态为编辑快照，免费不代表没有部署成本。具体额度、限制和地区支持请以官方页面为准。</p>`;}
function sourcesView(){return `<div class="section-head"><div><h2>靠近信息最初发生的地方<span class="small-label">SOURCE MAP</span></h2><p>官方确认、专业解释、社区体验，各自回答不同的问题。</p></div></div><div class="source-flow">${[['01','原始发布','Original'],['02','官方确认','Official'],['03','专业解释','Professional'],['04','社区讨论','Community'],['05','大众传播','Distribution']].map(([n,t,en])=>`<div><span>${n}</span><h3>${t}</h3><small>${en}</small></div>`).join('')}</div><p class="footnote">来源等级不是质量评分。这里标注已知来源角色；不把官网入口自动认定为最早首发。</p><div class="source-list">${db.sources.filter(s=>c.sourceIds.includes(s.id)).map(s=>`<article><span class="source-tier">${escape(s.tier)}</span><div><h3>${link(s.url,s.name)}</h3><p>${escape(s.description)}</p></div><span class="source-date">${s.checkedAt?'查阅 '+escape(s.checkedAt):'入口待复核'}</span></article>`).join('')}</div>`;}
function accessView(){return `<div class="section-head"><div><h2>你已经可以获得的能力<span class="small-label">YOUR ACCESS</span></h2><p>找到入口，也看清条件与下一步。</p></div><label class="select-label">我的身份 <select id="identity"><option value="all" ${identity==='all'?'selected':''}>普通用户</option><option value="student" ${identity==='student'?'selected':''}>在读学生</option><option value="developer" ${identity==='developer'?'selected':''}>开发者</option></select></label></div><div class="access-list">${selectedResources().map(r=>{const a=db.access.find(a=>a.id===r.accessId);if(!a)return '';const possible=a.eligibility==='all'||a.eligibility===identity;return `<article id="access-${escape(r.id)}" class="access-card"><div class="access-heading"><h3>${escape(r.name)}</h3><span class="badge ${possible?'green-badge':'amber'}">${possible?'可进一步核对申请条件':'需要学生身份'}</span></div><p class="access-how">${escape(a.how)}</p><dl class="access-grid"><div><dt>身份 / 使用条件</dt><dd>${escape(a.conditions)}</dd></div><div><dt>费用</dt><dd>${escape(pricing[r.pricing]||r.pricing)}</dd></div><div><dt>地区限制</dt><dd>${escape(a.region)}</dd></div><div><dt>时间窗口</dt><dd>${escape(a.window)}</dd></div></dl><div class="card-actions">${link(db.sources.find(s=>s.id===a.sourceId)?.url||r.url,'查看官方条件并获取')}<span>${a.alternativeIds.length?'其他可选：'+a.alternativeIds.map(id=>escape(db.resources.find(r=>r.id===id)?.name)).join('、'):'暂无收录同类替代'}</span></div></article>`;}).join('')}</div>`;}
function frontierView(){return `<div class="section-head"><div><h2>人类还没有走完哪里<span class="small-label">THE NEXT FRONTIER</span></h2><p>先辨别成熟能力，再为真正的问题寻找证据。</p></div></div><div class="frontier-summary"><article><span class="badge green-badge">已经成熟</span><h3>可以直接复用</h3>${c.frontier.mature.map(x=>`<p>✓ ${escape(x)}</p>`).join('')}</article><article><span class="badge amber">正在发展</span><h3>值得保持关注</h3>${c.frontier.growing.map(x=>`<p>↗ ${escape(x)}</p>`).join('')}</article></div><h3 class="gap-title">值得验证的未解决问题 <span>研究假设，不是市场结论</span></h3><div class="cards">${c.frontier.gaps.map((g,i)=>`<article class="gap-card"><span class="gap-number">0${i+1}</span><h3>${escape(g.title)}</h3><p>${escape(g.evidence)}</p><details><summary>如何验证这个方向</summary><p>${escape(g.experiment)}</p></details><button data-create="${i}">从这里继续创造 ↗</button></article>`).join('')}</div>`;}
function render(){const focused=document.activeElement?.id;$('#app').innerHTML=shell();bind();if(focused==='identity')$('#identity')?.focus();}
function bind(){
 $('#home').onclick=e=>{e.preventDefault();navigate(db.cases[0].id);};
 document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>navigate(b.dataset.topic));
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;filter='all';render();});
 document.querySelectorAll('[data-node]').forEach(b=>activate(b,()=>{selected=Number(b.dataset.node);edgeSelected=null;render();document.querySelector(`[data-node="${selected}"]`)?.focus();}));
 document.querySelectorAll('[data-edge]').forEach(b=>activate(b,()=>{edgeSelected=Number(b.dataset.edge);render();document.querySelector(`[data-edge="${edgeSelected}"]`)?.focus();}));
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});
 document.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>{tab='access';render();document.getElementById('access-'+b.dataset.access)?.scrollIntoView({behavior:'smooth',block:'center'});});
 document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>openCreation(Number(b.dataset.create)));
 $('#query-form').onsubmit=e=>{e.preventDefault();submit(false);};$('#query').oninput=e=>{query=e.target.value;};
 $('#custom-ai').onclick=()=>submit(true);
 $('#new-query').onclick=()=>{$('#query').focus();$('#query').select();};
 $('#failures')?.addEventListener('click',()=>{showFailures=!showFailures;render();});
 $('#node-resources')?.addEventListener('click',()=>{tab='solutions';render();});
 $('#identity')?.addEventListener('change',e=>{identity=e.target.value;render();});
 $('#zoom-in')?.addEventListener('click',()=>{zoom=2;render();});$('#zoom-out')?.addEventListener('click',()=>{zoom=1;render();});
 $('#export').onclick=()=>download(`${c.id}-exploration.md`,report());
 $('#bill').onclick=()=>openDialog(`<span class="eyebrow">INTERNET ACCESS BILL</span><h2>不知道，不应该等于没有。</h2><p>这里的“权利”是产品理念，不是法律意义上的法定权利。</p>${['发现权：发现尚不知道的资源与能力。','溯源权：理解方案从哪里来，为什么演化。','首发知情权：靠近信息的一手来源。','获得权：找到合法开放能力的实际入口。','选择权：了解多种成熟路径。','复用权：不必重复构建成熟基础。','来源透明权：事实和判断可以追溯。','行动权：把信息变成明确下一步。'].map(x=>`<p class="bill-item">${x}</p>`).join('')}`);
 $('#about').onclick=()=>openDialog('<span class="eyebrow">SOURCEVER</span><h2>先继承，再创造。</h2><p>这个 MVP 把需求、历史路线、资源、来源和获取方式连接在一起。</p><p>精选案例采用公开通用领域。历史图是编辑整理的概括性路线，不是完整历史。没有可靠来源时，我们保留缺口。</p><p>配置 AI 后，任意需求会发送到你选择的模型服务，返回尚未经过实时检索与事实核验的研究草稿。模型生成的来源仍需人工查验。</p><p>本版不包含实时雷达、账号、自动申请权益或实时爬虫。</p>');
 $('.dialog-close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close();});
}
function activate(el,fn){el.onclick=fn;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn();}};}
async function submit(forceAI){if(busy)return;query=$('#query').value.trim();if(query.length<2){error='请至少输入 2 个字符，描述想做到的事情。';render();$('#query').focus();return;}busy=true;error='';render();try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,forceAI})});const data=await r.json();if(!r.ok)throw new Error(data.error);c=data.case;for(const key of ['resources','sources','access'])db[key]=[...db[key].filter(x=>!data[key].some(y=>y.id===x.id)),...data[key]];tab='history';selected=2;edgeSelected=null;showFailures=false;zoom=1;history.replaceState(null,'',c.mode==='ai'?'#research':`#${c.id}`);if(data.matched)error='已找到相关精选案例。下方内容是该领域的编辑研究，不是对本次输入的实时分析。';}catch(e){error=e.message;}finally{busy=false;render();}}
function openDialog(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
function report(){return `# ${c.title}\n\n输入：${query}\n\n底层需求：${c.need}\n\n模式：${c.mode==='ai'?'AI 草稿，未经核验':'精选编辑案例'} · ${c.updatedAt}\n\n## 历史演化\n${c.nodes.map(n=>`### ${n.name} · ${n.era}\n解决：${n.solves}\n限制：${n.limitation}\n解释：${n.reason}\n`).join('\n')}\n## 关键跃迁\n${c.edges.map(e=>`- ${c.nodes.find(n=>n.id===e.fromId)?.name} → ${c.nodes.find(n=>n.id===e.toId)?.name}：${e.why}；新问题：${e.newProblem}`).join('\n')}\n\n## 可复用资源与获取\n${selectedResources().map(r=>`- [${r.name}](${r.url})：${db.access.find(a=>a.id===r.accessId)?.how}`).join('\n')}\n\n## 失败路线\n${c.failures.map(f=>`${f.name}：${f.reason} ${f.lesson}`).join('\n')||c.failureNote}\n\n## 创新边界（假设）\n${c.frontier.gaps.map(g=>`- ${g.title}：${g.evidence} 验证：${g.experiment}`).join('\n')}\n\n## 来源\n${db.sources.filter(s=>c.sourceIds.includes(s.id)).map(s=>`- [${s.name}](${s.url}) · ${s.tier} · ${s.checkedAt||'待核验'}`).join('\n')}\n`;}
function creationText(g,type){const resources=selectedResources().map(r=>`- ${r.name}：${r.url}`).join('\n');if(type==='research')return `# ${g.title} · 研究任务\n\n底层需求：${c.need}\n\n待验证假设：${g.evidence}\n\n${g.experiment}\n\n1. 观察目标用户最近一次任务，记录已有替代方案与失败点。\n2. 通过下列官方来源查找同类方案、开源实现和失败复盘。\n3. 对价格、地区、资格与版本逐项核验，不沿用旧快照。\n4. 只有当现成方案无法解决经过观察的问题时，才设计新产品。\n\n${resources}\n`;
 return `# ${g.title} · ${type==='prd'?'PRD':'MVP'} 工作草案\n\n> 基于能力图谱生成的本地模板；未经用户研究验证。\n\n## 问题\n${c.need}\n\n## 待验证机会\n${g.title}\n${g.evidence}\n\n## 目标用户\n待访谈确认：实际遇到“${g.title}”问题的人。\n\n## 复用基础能力\n${resources}\n\n## 最小验证范围\n只完成一条围绕“${g.title}”的任务路径。用现成能力搭建原型，不重做${c.frontier.mature.join('、')}。\n\n## 用户流程\n选择一份真实任务输入 → 执行原型支持的关键步骤 → 与原有方案比较结果 → 记录反馈。\n\n## 验收与实验\n${g.experiment}\n记录任务完成率、耗时、错误次数与用户是否愿意再次使用；阈值应在基线测试后预先约定。\n\n## 非目标\n完整平台、账号体系、支付、未经验证的大规模自动化。\n\n## 风险和待决策\n数据权限、集成可行性、迁移成本、来源准确性及需求频率待验证。\n\n## 下一步\n先完成访谈与替代方案比较，再决定是否开发。\n`;}
function openCreation(index){const g=c.frontier.gaps[index];creation={g,type:'mvp'};openDialog(`<span class="eyebrow">BUILD FROM HERE</span><h2>${escape(g.title)}</h2><p>把尚未解决的问题，转成一份可验证的行动草案。</p><label class="select-label">下一步 <select id="creation-type"><option value="mvp">设计 MVP</option><option value="prd">生成 PRD 草案</option><option value="research">深入研究 / 寻找开源实现</option></select></label><textarea id="creation-text" rows="15" aria-label="可编辑的创造草案">${escape(creationText(g,'mvp'))}</textarea><button class="primary" id="download-creation">下载 Markdown ↓</button><button class="outline" id="copy-creation">复制草案</button><p id="copy-status" role="status"></p>`);$('#creation-type').onchange=e=>{creation.type=e.target.value;$('#creation-text').value=creationText(g,creation.type);};$('#download-creation').onclick=()=>download(`${c.id}-${creation.type}.md`,$('#creation-text').value);$('#copy-creation').onclick=async()=>{try{await navigator.clipboard.writeText($('#creation-text').value);$('#copy-status').textContent='已复制到剪贴板';}catch{$('#creation-text').select();$('#copy-status').textContent='请使用 Ctrl+C / ⌘C 复制已选中的草案';}};}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!$('#dialog')?.open){e.preventDefault();$('#query')?.focus();}});
try{const r=await fetch('/api/bootstrap');if(!r.ok)throw new Error();db=await r.json();baseDb=structuredClone(db);c=db.cases.find(x=>x.id===location.hash.slice(1))||db.cases.find(x=>x.id==='collaboration')||db.cases[0];query=c.want;render();}catch{$('#app').innerHTML='<div class="initial"><h1>图谱暂时无法加载</h1><p>请确认本地服务已启动，再刷新页面。</p><a href="/">重新打开页面</a></div>';}
